### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by bittner** [bittner/pyclean#12]
Travis CI still doesn't support Python on neither macOS nor Windows. As GitHub Actions now seems to support [all three platforms](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#using-the-default-python-version) we need to run our tests against, it makes sense to move there.

Example
-----------

```yaml
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
```

Related resources
----------------------

- [Documentation > Configuring a workflow > Choosing a runner](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#choosing-a-runner)
- [Documentation > Using Python with GitHub Actions](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions)
- [Example setup](https://github.com/actions/setup-python/blob/master/.github/workflows/workflow.yml#L17)
